# Generated by Django 4.0.5 on 2022-06-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
