# Generated by Django 4.0.5 on 2022-06-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_alter_myuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_photo',
            field=models.ImageField(default='image/default.jpg', upload_to='profile_images/'),
        ),
    ]
