# Generated by Django 4.0.5 on 2022-06-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0004_myuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_photo',
            field=models.ImageField(default='static/image/default.jpg', upload_to='profile_images/'),
        ),
    ]
