# Generated by Django 4.0.5 on 2022-06-21 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionDetails',
            fields=[
                ('auction_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('auction_details_date', models.DateField()),
                ('auction_start_time', models.DateTimeField()),
                ('auction_time_span', models.DurationField()),
                ('product_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller_app.productinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('bidder_id', models.AutoField(primary_key=True, serialize=False)),
                ('bidder_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAuction',
            fields=[
                ('current_auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('auction_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Auction_app.auctiondetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserWishlist',
            fields=[
                ('user_wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('wishlisted', models.BooleanField()),
                ('auction_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction_app.auctiondetails')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDeposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amt', models.BigIntegerField()),
                ('currentauction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction_app.currentauction')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentBid',
            fields=[
                ('current_bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_bid_time', models.DateTimeField(auto_now=True)),
                ('current_bid_amt', models.BigIntegerField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction_app.bidder')),
                ('currentauction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction_app.currentauction')),
            ],
        ),
        migrations.AddField(
            model_name='bidder',
            name='currentauction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction_app.currentauction'),
        ),
        migrations.AddField(
            model_name='bidder',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AutoBid',
            fields=[
                ('autobid_id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_price', models.BigIntegerField()),
                ('increment_price_by', models.BigIntegerField()),
                ('max_price', models.BigIntegerField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction_app.bidder')),
            ],
        ),
        migrations.CreateModel(
            name='AllBid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_time', models.DateTimeField()),
                ('bid_amt', models.BigIntegerField()),
                ('auctiondetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction_app.auctiondetails')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
