# Generated by Django 4.0.5 on 2022-06-21 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('product_sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_sub_category_name', models.CharField(max_length=100)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller_app.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('product_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_info_details', models.TextField()),
                ('product_verify', models.BooleanField()),
                ('product_baseprice', models.BigIntegerField()),
                ('is_sold', models.BooleanField(default=False)),
                ('product_location', models.CharField(max_length=50)),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller_app.productsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('product_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_image', models.ImageField(upload_to='ProductPhotos/')),
                ('product_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller_app.productinformation')),
            ],
        ),
    ]
