# Generated by Django 4.0.5 on 2022-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinformation',
            name='product_verify',
            field=models.BooleanField(default=False),
        ),
    ]
