# Generated by Django 4.0.5 on 2022-06-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_app', '0002_alter_productinformation_product_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinformation',
            name='product_verify',
            field=models.BooleanField(),
        ),
    ]
